name: Activity Box template

on:
  schedule:
    - cron: '*/1 * * * *'
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: JasonEtco/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_ACT_TEMPLATE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: knight-moon-72
          GIST_ID: f3c39a04a04a51d45758117985e25b7a
